spring:
  datasource:
    url: jdbc:mysql://localhost:3306/appointment?user=root
    username: root
    password: 123456

    
  jpa.hibernate.ddl_auto: update
  

server:
  port: 8080



jwt:
  secret: secretkey123